### Site metadata ###

title: Jiaying's Portfolio
description: Welcome to Jiaying Wei's portfolio website.

### Build settings ###

url: ""
baseurl: ""

exclude:
  - assets/images/archive
  - portfolio/archive
  - bin/
  - vendor/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - package*.json
  - yarn.lock
  - postcss.config.js
  - purgecss.config.js
  - README.md
  - Makefile
  - netlify.toml

# include:
#   - node_modules/
#   - vendor/




